<!DOCTYPE html>
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title>{{ title }} – kolibri.io</title>
    {{ assets.outputCss() }}
</head>
<body class="antialiased">
{% include "partials/header.phtml" %}
{{ content() }}
{% include "partials/footer.phtml" %}
{{ assets.outputJs() }}
{% if page is empty %}
{% else %}
    <div id="delete" class="reveal-modal small">
        <h2>Are you certain?</h2>

        <p>Do you really want to delete this page? This can not be undone. We don't use soft-deletes. Yep,
            really.</p>
        <a class="close-reveal-modal">&#215;</a>
        {{ link_to("delete/" ~ page.id, "Yes, go ahead.", "class": 'button secondary') }}
    </div>
{% endif %}
<div id="shortcuts" class="reveal-modal small">
    <h3>Keyboard shortcuts</h3>

    <p>The following shortcuts are available in the appropriate context:</p>
    <dl>
        <dt>Create new page</dt>
        <dd><kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>a</kbd></dd>
        <dt>Edit the current page</dt>
        <dd><kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>e</kbd></dd>
        <dt>Save currently open form</dt>
        <dd><kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>s</kbd></dd>
    </dl>
    <a class="close-reveal-modal">&#215;</a>
</div>
</body>
</html>
