<div class="row login">
    <div class="small-6 large-centered columns">
        <h1>Login required</h1>
        <p>This wiki is password protected. Please provide the password to login for this session.</p>
        {{ form('login', 'id': 'login') }}
        <input type="password" name="password" id="password" placeholder="Password" />
        <button type="submit" class="right">Login</button>
        </form>
    </div>
</div>