<div class="inner cover">
<h1 class="cover-heading">Login required</h1>
<p class="lead">This wiki is password protected. Please provide the password to login for this session.</p>
{{ form('login', 'id': 'login', 'class': 'form-horizontal', 'role': 'form') }}
<div class="form-group">
	<label for="password" class="col-sm-2 control-label">Password</label>
	<div class="col-sm-10">
		<input type="password" name="password" class="form-control" id="password" placeholder="Password">
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default">Login</button>
	</div>
</div>
</form>
</div>