<ol class="breadcrumb">
	<li>{{ link_to("", "~") }}</li>
	<li>{{ link_to("page/"~page.title, page.title) }}</li>
	<li>Revisions</li>
</ol>
<h1>Revisions of <em>{{ page.title }}</em></h1>
{% if versions is iterable %}
    <ul>
        {% for version in versions %}
            <li>{{ link_to("version/"~version.page_id~"/"~version.version, "Revision #" ~ version.version) }}<br/>
                <small>created at {{ version.created }}</small>
            </li>
        {% endfor %}
    </ul>
{% endif %}